### ISSUE TITLE
Release .sig files are not available

### ISSUE THREAD

**Issue by erasmospunk** [keepassxreboot/keepassxreboot.github.io#10]
The page https://keepassxc.org/verifying-signatures documents a way to check the PGP signature:

`gpg --verify KeePassXC-$VERSION-x86_64.AppImage.sig`

however there are no .sig files in the https://keepassxc.org/download section

**Comment by TheZ3ro** [comment]
Only official cross-distribution packages are signed with our PGP key, snap is automatically checked and the AppImage have its .sig (GPG signature)
![istantanea_2017-04-07_18-52-47](https://cloud.githubusercontent.com/assets/686894/24810682/756e0914-1bc3-11e7-9235-28f5f1e2c7d6.png)
