### ISSUE TITLE
Implement Flathub.org verification

### ISSUE THREAD

**Issue by loganmarchione** [keepassxreboot/keepassxreboot.github.io#108]
Not sure if this belongs in this repo or the [packaging](https://github.com/keepassxreboot/keepassxc-packaging) repo...

The official KeePassXC [download page](https://keepassxc.org/download/#linux) has instructions to install via Flatpak. Who maintains this [Flatpak on Flathub](https://flathub.org/apps/details/org.keepassxc.KeePassXC) (repo [here](https://github.com/flathub/org.keepassxc.KeePassXC))? I'm assuming that since Flatpak is mentioned on keepassxc.org that it's officially maintained by KeePassXC. Per [this](https://github.com/keepassxreboot/keepassxc/issues/1524#issuecomment-1100282347), the Flatpak is official, right?

If that is the case, you should look into verifying your application on Flathub. Flathub's Beta site is rolling out blue-checkmark verification so that the community knows that the Flatpak app is official from the developer.

The Flathub Beta site has an [entire section of verified applications](https://beta.flathub.org/apps/collection/verified). For example, look at the blue checkmarks on [LibreOffice](https://beta.flathub.org/apps/org.libreoffice.LibreOffice), [Firefox](https://beta.flathub.org/apps/org.mozilla.firefox), and [OBS](https://beta.flathub.org/apps/com.obsproject.Studio).

There is a post [here](https://discourse.flathub.org/t/how-do-you-get-a-flathub-submission-verified/3714) about how to get verified.

Being verified would let users know that one of their most important apps (a password manager) is directly from the developer, not a third-party. Plus, you could add the word "Official" to the Flatpak on the Download page, like AppImage and Snap have.

**Comment by droidmonkey** [comment]
Done!
![image](https://user-images.githubusercontent.com/2809491/221375161-963e1dd8-e2e9-4152-9e61-f1b6b615fd17.png)
