### ISSUE TITLE
Add some screenshots to the website.

### ISSUE THREAD

**Issue by louib** [keepassxreboot/keepassxreboot.github.io#11]
Requested by @Wandmalfarbe
> It would be nice to know what the program looks like before downloading and installing it.

**Comment by matthewdavis** [comment]
This should be most of the relevant views.

![keepassxc1-root](https://cloud.githubusercontent.com/assets/298426/26422915/9ac6893e-4099-11e7-816e-cdff5f75d558.png)
![keepassxc2-autotype](https://cloud.githubusercontent.com/assets/298426/26422912/9ac3fbe2-4099-11e7-99a9-198021ee216b.png)
![keepassxc3-edit](https://cloud.githubusercontent.com/assets/298426/26422916/9ac75094-4099-11e7-8b40-7140705e6b7d.png)
![keepassxc4-passgen](https://cloud.githubusercontent.com/assets/298426/26422914/9ac5d37c-4099-11e7-9cad-ac6f2183f449.png)
![keepassxc5-passphrase](https://cloud.githubusercontent.com/assets/298426/26422918/9accbfa2-4099-11e7-92ae-c56c3069ee03.png)
![keepassxc6-settings1](https://cloud.githubusercontent.com/assets/298426/26422917/9ac8f368-4099-11e7-8cd4-56e3c2a0e1b2.png)
![keepassxc7-settings2](https://cloud.githubusercontent.com/assets/298426/26422919/9ad0654e-4099-11e7-9bc4-9544e9f76daf.png)
![keepassxc8-settings3](https://cloud.githubusercontent.com/assets/298426/26422922/9ad3aff6-4099-11e7-914e-abbefe1bb728.png)
![keepassxc9-settings4](https://cloud.githubusercontent.com/assets/298426/26422920/9ad29486-4099-11e7-8c96-43b6f1c49874.png)
![keepassxc10-settings5](https://cloud.githubusercontent.com/assets/298426/26422923/9ad4ab54-4099-11e7-88d8-466d7c72e4c8.png)
![keepassxc11-favicon](https://cloud.githubusercontent.com/assets/298426/26422921/9ad3628a-4099-11e7-9e4c-f8c16655779a.png)

**Comment by hifi** [comment]
Even though I'm also an avid Xfce user, none of the default xfwm themes look very modern.

I'd think taking screenshots on the default light KDE Plasma 5 theme could yield one of the best results for Qt applications.

It'd also be nice and consistent to have a paswordless screenshot database for KeePassXC that has a standard set of entries with custom icons where applicable so current and future screenshots would be similiar.
