### ISSUE TITLE
Add RSS feed link to website

### ISSUE THREAD

**Issue by aurmil** [keepassxreboot/keepassxreboot.github.io#110]
hello,
did you intentionnaly remove this RSS/Atom feed or is it a mistake?

**Comment by aurmil** [comment]
seems OK with my RSS feed aggregator

**Comment by JacksonChen666** [comment]
Why was this closed as not planned?

**Comment by droidmonkey** [comment]
The RSS is now at index.xml

**Comment by JacksonChen666** [comment]
I have some issues with it:
1. It doesn't work anymore in Thunderbird (it used to, until the website changed)
2. The new RSS/Atom didn't seem like it was linked in places related to the blog, so it's hard to find (no, this github issue should not be a source of information on where the RSS feed is)

(Note: these observations are not current, but I doubt it's invalid since it there hasn't been changes to the repo for the website)

**Comment by droidmonkey** [comment]
You need to fix your Thunderbird, see above link. 

I wasnt even aware we had an rss feed, I guess we can add it to the footer...

**Comment by JacksonChen666** [comment]
I have alredy tried adding a new RSS feed with the new URL in thunderbird, then that little error came up.

**Comment by droidmonkey** [comment]
No the link to the bug report to Thunderbird

https://support.mozilla.org/en-US/questions/1166672

**Comment by phoerious** [comment]
I added a 301 redirect from https://keepassxc.org/blog/feed.xml to https://keepassxc.org/blog/index.xml. Hope that solves it for now.

**Comment by phoerious** [comment]
The challenge should be valid for about 30 minutes. I reduced the security level a bit, try again.

**Comment by JacksonChen666** [comment]
> The challenge should be valid for about 30 minutes. I reduced the security level a bit, try again.

Cloudflare is still bothering me with checks.


> That said, we are getting a lot of Tor requests at the moment and had a traffic peak that looked quite suspicious.

<sup><sup><sup>(What are you protecting against again?)</sup></sup></sup>

**Comment by phoerious** [comment]
I disabled Cloudflare's onion routing. Are you still getting Captchas?

**Comment by JacksonChen666** [comment]
> I disabled Cloudflare's onion routing. Are you still getting Captchas?

Still getting captchas (or just Cloudflare requiring cookies), but I'm not using the onion address (nor can I find an onion address for keepassxc.org)

Should we maybe move this into a new issue to stop bothering with others here?

**Comment by phoerious** [comment]
Then that's maybe your non-standard user agent. Browser integrity check is off now.

**Comment by JacksonChen666** [comment]
> Then that's maybe your non-standard user agent. Browser integrity check is off now.

Still getting captcha.

**Comment by phoerious** [comment]
And now?

**Comment by JacksonChen666** [comment]
> And now?

No captcha! Not at all.

**Comment by phoerious** [comment]
Still?

**Comment by JacksonChen666** [comment]
> Still?

No captcha.

**Comment by phoerious** [comment]
Okay, then I'll leave it at that for now.
