### ISSUE TITLE
Website addition re Mac sha256 DIGEST check instructions - use shasum

### ISSUE THREAD

**Issue by bunk3m** [keepassxreboot/keepassxreboot.github.io#12]
## Expected Behavior
On the website [https://keepassxc.org/verifying-signatures](url) the suggestion is to use sha256 command.  This command isn't available on the Mac.  It would be nice to update the website with Mac specific instructions.

## Current Behavior
To verify the download I had to go searching for a way to check the sha256 digest.  Not impossible of course, but it would be nice to have the instructions on the website.

## Possible Solution
Command shasum can be used instead of sha256.  I recommend adding the following command for verifying the Mac DMG.

`shasum -a 256 -c KeePassXC-[Version].dmg.DIGEST`

## Context
Instead of having to search for the way to check the Digest, it would be nice to have instructions on the website.

Command above allowed me to verify the DMG.

## Your Environment
OSX 10.10.5

**Comment by TheZ3ro** [comment]
Should be fixed now! Thanks for the report :wink:

**Comment by bunk3m** [comment]
@TheZ3ro Thank you.  Looks good so far.

The stuff you removed probably works for Win & Linux though.  What I suggested was in addition to what was already there.

I don't think there is a shasum command in Linux.  You need to use the sha256sum command (Ubuntu)

**Comment by TheZ3ro** [comment]
On my Ubuntu there is the shasum command exactly as for Mac OS, for windows you have to download an external program to do the shasum

**Comment by phoerious** [comment]
IIRC Windows also has a cmd tool for that, but its usage is a little more difficult.
