### ISSUE TITLE
GPG fetch keys error

### ISSUE THREAD

**Issue by twdkeule** [keepassxreboot/keepassxreboot.github.io#15]
When fetching the keys as stated on https://keepassxc.org/verifying-signatures, I get the fllowing error:
```
$ gpg --fetch-keys https://keepassxc.org/keepassxc_master_signing_key.asc                       
gpg: requesting key from 'https://keepassxc.org/keepassxc_master_signing_key.asc'
gpg: WARNING: unable to fetch URI https://keepassxc.org/keepassxc_master_signing_key.asc: No data
```

**Comment by TheZ3ro** [comment]
I can replicate this on xUbuntu

What operative system are you using? 
Please don't delete the issue template the next time

**Comment by twdkeule** [comment]
There was no issue template?
I am using Ubuntu 17.04

**Comment by TheZ3ro** [comment]
@twdkeule you are right about the issue template apparently :smile: 

Can you try on this key as well? 
`gpg --fetch-keys https://keys.qubes-os.org/keys/qubes-master-signing-key.asc`

PS: in the meantime you can download the key with `wget` or `curl` and then import it

**Comment by twdkeule** [comment]
keys.qubes-os.org/keys works!

**Comment by TheZ3ro** [comment]
On my system both keys fail. 

Qubes one has `Content-Type: application/pgp-signature`, our instead is `Content-Type: text/plain`

Can we do something about this? @phoerious

**Comment by phoerious** [comment]
I'm not quite sure what's wrong there. The GPG documentation kind of says that --fetch-keys is for fetching keys from a given URL. But may it only works with keyservers, who knows. I can't really find any other information on this matter.

When I send a HEAD request, the only real difference between Qubes and our key is the Content-Type header. But when I change that, the result is still the same. But I tried both URLs and as @TheZ3ro described, too, both fail. So maybe --fetch-keys isn't supposed to work this way after all.

Maybe we should change the command to `curl https://keepassxc.org/keepassxc_master_signing_key.asc | gpg --import`.

**Comment by twdkeule** [comment]
Maybe I'll fil a bug report for gpg.

Thanks for the responses!
