### ISSUE TITLE
Use minified CSS and JS for improved performance

### ISSUE THREAD

**Issue by coliff** [keepassxreboot/keepassxreboot.github.io#2]
Bootstrap's CSS and JS and Font Awesome's CSS are loading the unminified versions which negatively impacts performance.

**Comment by TheZ3ro** [comment]
fixed in commit https://github.com/keepassxreboot/keepassxreboot.github.io/commit/3aefae09610cdfe10b32494989d74cefe35e6f78

**Comment by coliff** [comment]
Nice! I think just the Bootstrap JS in the footer to update now....

**Comment by TheZ3ro** [comment]
Oh gosh. I forgot that. Now should be ok.
