### ISSUE TITLE
Add documentation about how KeepPassXC matches a site to an entry.

### ISSUE THREAD

**Issue by ericmoritz** [keepassxreboot/keepassxreboot.github.io#39]
I didn't know how KeepassXC matches a website to an entry.  I know it matches in the URL but Keepass2Android uses the URL field for the Android app entry (I wish they used a additional attribute for that).

I assumed that if the entry's title was a substring of the domain name, it would match.  I digged into the code and it turns out that it matches if the domain name ends with the title.

Could that be documented somewhere `keepassxc-browser-migration.md`?

**Comment by droidmonkey** [comment]
This will be covered by our documentation set being developed (outside the scope of the website)
