### ISSUE TITLE
Documentation for keepassxc-cli not readily available

### ISSUE THREAD

**Issue by linuxrichard** [keepassxreboot/keepassxreboot.github.io#41]
There is nothing on the website indicating keepassxc-cli's existence.
Although there is a manpage in one(?) of the packages, there is nothing on the website and nothing for the Windows package other than the keepassxc-cli.exe -?
This is a very useful package and it is sad that it is hidden away in this way. I had even started at looking at building this myself because I didn't know it existed!

I suggest that the website have a page or section added that:
- highlights that keepassxc-cli exists
- explains its purpose
- provides the syntax (extract from the manpage?) ([is this the official manpage](https://www.mankier.com/1/keepassxc-cli)?)
(This is a duplicate of [keepassxc/issues/1983](https://github.com/keepassxreboot/keepassxc/issues/1983) because there is no documentation that I can find to actually put on the website.

**Comment by TheZ3ro** [comment]
We should also make a page for the browser plugin at some point.
