### ISSUE TITLE
Lacking Documentation for Browser Extension String Fields

### ISSUE THREAD

**Issue by cadyb** [keepassxreboot/keepassxreboot.github.io#45]
Having information on how to use the browser extensions custom strings added to the browser section of the FAQ may make it more visible and easier to find for users looking to use this feature.

See: keepassxreboot/keepassxc-browser#122

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxreboot.github.io/blob/564120a8619b70f73f720fffd293f45282f06f5d/docs/keepassxc-browser-manual.md#17-fill-additional-values-using-string-fields - this is from #43

**Comment by droidmonkey** [comment]
This is now added
