### ISSUE TITLE
Add Slackware to "Distribution-specific packages"

### ISSUE THREAD

**Issue by bosth** [keepassxreboot/keepassxreboot.github.io#52]
Here's information required to have the Slackware build script for KeepassXC included on the Download page:

**Slackware**

Slackware SlackBuild: https://slackbuilds.org/apps/keepassxc/

**Comment by phoerious** [comment]
We don't want too many niche distributions there, otherwise the page just grows with every fringe Linux derivative. I know that Slackware has an active user base, but it's not really what I would call a mainstream distro.

**Comment by bosth** [comment]
Fair enough if you don't want to clutter up the Download page - Slackware is no Ubuntu or Fedora in terms of users, but it is at least the oldest surviving Linux distro so I'd like to think it's not fringe at least :smile:

**Comment by phoerious** [comment]
It's old, but not gold I'd say. It served us well... fifteen years ago. 😉
