### ISSUE TITLE
I want to say thanks with a Bitcoin Cash donation

### ISSUE THREAD

**Issue by emergent-reasons** [keepassxreboot/keepassxreboot.github.io#56]
Could you guys add an address for BCH on [donations](https://github.com/keepassxreboot/keepassxreboot.github.io/blob/master/donate.html)?

**Comment by droidmonkey** [comment]
Howdy, you can donate to this wallet:

bitcoincash:qzn2rwdeuxe04d38q53362rd45ljqlw2rqun0pmhxl

**Comment by droidmonkey** [comment]
I added it to the website as well, you can see my verified commit here: https://github.com/keepassxreboot/keepassxreboot.github.io/commit/ba1f4fc544fa1bb8f16c71986e6097ecb2b4db52

**Comment by emergent-reasons** [comment]
Woo thanks!

**Comment by droidmonkey** [comment]
Thank you for your support!
