### ISSUE TITLE
Document KeeShare

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxreboot.github.io#57]
There seems to be a new feature called "KeeShare" in v2.4.0, but I mostly just see empty GUIs with empty list views.
I also see buttons that do nothing ("trust", "do not trust", …) and in the database settings I see another GUI that has an entirely empty list view and no way to insert anything/interact.

This feature is really puzzling for me…

It's also nowhere documented.
So can you maybe add some FAQ items or even a bigger doc?

What is it? What can I do with it? How do I even use it? What is it for?

**Comment by droidmonkey** [comment]
I'm closing this in favor of the one in the application repository.
