### ISSUE TITLE
Improve Q&A `Does KeePassXC work on mobile phones?`

### ISSUE THREAD

**Issue by sarpik** [keepassxreboot/keepassxreboot.github.io#61]
Hello,
I was wondering if I can use keepassxc on android and I came across the documentation's q&a - https://keepassxc.org/docs/#faq-platform-mobile

and after reading it - it seemed like there's no solution for android / ios.

But then I came across this issue https://github.com/keepassxreboot/keepassxc/issues/1060

and reached this comment
https://github.com/keepassxreboot/keepassxc/issues/1060#issuecomment-442347384

saying that we can freely use keepassxc on android, and suggesting to relax the warning.

---

So I forked this repo and I'm about to submit a PR for it - I might not make everything correct, so feel free to add suggestions / code reviews before accepting.

**Comment by droidmonkey** [comment]
No need to create an issue and PR. We'll just focus on the PR.
