### ISSUE TITLE
Is there a list of shortcut keys?

### ISSUE THREAD

**Issue by matcharles** [keepassxreboot/keepassxreboot.github.io#66]
I have pressed some combinaison of keys and now have the passwords show in clear text. I would like to go back to asterix but can't find it? Thanks!

**Comment by droidmonkey** [comment]
Ctrl+Shift+C

Keyboard shortcuts are available here: https://github.com/keepassxreboot/keepassxc/blob/develop/docs/KEYBINDS.md
