### ISSUE TITLE
Add link to Github `docs` folder on documentation page

### ISSUE THREAD

**Issue by frederickjh** [keepassxreboot/keepassxreboot.github.io#70]
My reasoning behind this request is that the website tends to behind the Github documentation. If a link is added under the **Documentation** point in the website menu, something like "**Github Documentation**", This will make it easier for new non-coder users to find this information. 

One cannot expect that a new user that is a non-coder will have any idea that:
1. they know what Github is
2. the code for KeePassXC is on Github
3. that there could be helpful documentation there

Please consider adding a link to the menu under document to the Github `docs` folder.

Also, please consider a full review of the documentation in the Github `docs` folder to see if the information contained therein is also present on the website.

**Comment by droidmonkey** [comment]
Technically the GitHub docs is for the develop branch, unreleased version. We are reformulating our documentation for 2.6.0 to be more uniformly accessible.

**Comment by frederickjh** [comment]
Just stumbled over this issue. Maybe add a link in the developer section to the Github docs or just close this issue.
