### ISSUE TITLE
Website not reachable

### ISSUE THREAD

**Issue by bin101** [keepassxreboot/keepassxreboot.github.io#71]
Hi

Most of the time I cannot access the website.

Chromium responds with "DNS_PROBE_FINISHED_NXDOMAIN". Firefox also has the same result.

I also tried different DNS server (8.8.8.8 from google, 1.1.1.1 from cloudfare and from my ISP).

**Comment by droidmonkey** [comment]
What country are you in?

**Comment by bin101** [comment]
Germany

**Comment by bin101** [comment]
nvm I think this was a local issue
