### ISSUE TITLE
Link to winget-pkgs manifest broken

### ISSUE THREAD

**Issue by ludetje** [keepassxreboot/keepassxreboot.github.io#91]
Hi!

The structure of the winget-pkgs manifest repo seems to have changed. Now the link to it on the download page is broken.
Line 380 in File [download.html](https://github.com/keepassxreboot/keepassxreboot.github.io/blob/master/download.html) points to https://github.com/microsoft/winget-pkgs/tree/master/manifests/KeePassXCTeam/KeePassXC. 
The manifests are now structured in subfolders by initial letter of the project.

Therefore line 380:
`<a href="https://github.com/microsoft/winget-pkgs/tree/master/manifests/KeePassXCTeam/KeePassXC">`

needs to be changed to:
`<a href="https://github.com/microsoft/winget-pkgs/tree/master/manifests/k/KeePassXCTeam/KeePassXC">`

Hopefully this issue report is at the right place.

**Comment by droidmonkey** [comment]
Thanks, right place 😁
